### PR TITLE
Första lektion i Java

### PR DESCRIPTION
**Pull request by PavelKostyuk**

### CODE REVIEW

**Comment by PavelKostyuk** [comment]
C:\Users\pavel\OneDrive\Skrivbord\GitHub-lessons\devops22-java\lesson_1\DebugHello.java
C:\Users\pavel\OneDrive\Skrivbord\GitHub-lessons\devops22-java\lesson_1\DebugHello.png
C:\Users\pavel\OneDrive\Skrivbord\GitHub-lessons\devops22-java\lesson_1\FirstHello.java
C:\Users\pavel\OneDrive\Skrivbord\GitHub-lessons\devops22-java\lesson_1\FirstHello.png
C:\Users\pavel\OneDrive\Skrivbord\GitHub-lessons\devops22-java\lesson_1\Java --version.png

**Comment by PavelKostyuk** [comment]
DebugHello
FirstHello
Java --version

**Comment by ripperdoc** [comment]
Saknar `javac --version` @PavelKostyuk

**Comment by PavelKostyuk** [comment]
Javac --version

**Comment by ripperdoc** [comment]
Done!

**Pull request closed without merging**
